name: smart_academic_scheduling
description: Smart Academic Scheduling System for Android

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  intl: ^0.19.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/css_logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/css_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/css_logo.png