// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfybRoQvGoVr1pTjzO2iFmTQg29WEF8ag',
    appId: '1:159018685995:web:2ac9e90d04f850d8dd3c6e',
    messagingSenderId: '159018685995',
    projectId: 'amcc-8d73f',
    authDomain: 'amcc-8d73f.firebaseapp.com',
    storageBucket: 'amcc-8d73f.firebasestorage.app',
    measurementId: 'G-VSF8X2QP8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeZfjx86WxU1f6vAQHd182pj8KZ0N_rvw',
    appId: '1:159018685995:android:bd6224ea23036da6dd3c6e',
    messagingSenderId: '159018685995',
    projectId: 'amcc-8d73f',
    storageBucket: 'amcc-8d73f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIjQSm7TMSErMuGCGFlE6N1PfGMDbXblA',
    appId: '1:159018685995:ios:865eabd0bb91a15bdd3c6e',
    messagingSenderId: '159018685995',
    projectId: 'amcc-8d73f',
    storageBucket: 'amcc-8d73f.firebasestorage.app',
    iosClientId: '159018685995-8ao01hd0lm5udsrep4dvv2615f211q2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomSync',
  );
}
